name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs_version: [18,19,20]
        operating_systems: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_systems: macos-latest
    name: Unit Testing
    runs-on: ${{matrix.operating_systems}}

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Install NodeJs version - ${{matrix.nodejs_version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.nodejs_version}}

    - name: Install Dependencies
      run: npm install
    
    - name: unity testing
      run: npm test

    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      with:
        name: moch-test-result-${{matrix.operating_systems}}-${{matrix.nodejs_version}}
        path: test-results.xml
    
  code_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup NodeJs Version 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Archive Test Result
      uses: actions/upload-artifact@v4
      with:
        name: Code-Coverage-Result
        path: coverage
        retention-days: 5
